version: "3.9"

services:
  manim:
    image: manimcommunity/manim:stable
    container_name: manim
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
